services:
  - type: web
    name: SKYLINE-MD
    runtime: python
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node index.js"
    repo: https://github.com/render/SKYLINE-REPO.git
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-app-db
          property: connectionString

databases:
  - name: SKYLINE-MD-db
    plan: free
